INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Silva', 'bnsilva5@gmail.com', '2021-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Geraldine', 'Murcia', 'geral@gmail.com', '2021-05-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Manuel', 'Silva', 'masr@gmail.com', '2021-06-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Juan', 'Gatillazo', 'juan_g@gmail.com', '2021-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicol', 'Paine', 'nicol_pain@gmail.com', '2021-01-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Maria', 'Ruiz', 'braindead@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tony', 'Silva Ruiz', 'brandon.silva@bitsamericas.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Eric', 'Foresta', 'bnsilva5@misena.edu.co', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Bet', 'Ruiz', 'silvaruizbrandon@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nicholas', 'Draven', 'forestatony@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Nathalie', 'Silva C', 'nathalie@false.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Rick', 'Allen', 'rick@true.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Joe', 'Elliot', 'joee123@def.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Milo', 'Rod', 'rodmilo@gmail.com', '2021-03-23');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('James', 'Hatfield', 'james@metallica.com', '2021-03-23');

